import * as fs from 'fs';
import * as readline from 'readline';
import { RawTranscriptStep, TokenMetrics, ConversationSession, PricingRates, ModelUsageMetrics } from '../types';
import { TokenizerService } from './tokenizer';
import { resolveModelPricing, DEFAULT_MODEL_KEY } from '../constants';

/**
 * Service to parse Antigravity JSONL transcripts and extract token metrics.
 */
export class TranscriptParser {
  private tokenizer: TokenizerService;

  constructor() {
    this.tokenizer = TokenizerService.getInstance();
  }

  /**
   * Parses a transcript.jsonl file completely or incrementally from an offset.
   */
  public async parseFile(
    filePath: string,
    conversationId: string,
    pricing: PricingRates
  ): Promise<ConversationSession | null> {
    if (!fs.existsSync(filePath)) {
      return null;
    }

    try {
      const stats = fs.statSync(filePath);
      const fileStream = fs.createReadStream(filePath, { encoding: 'utf8' });
      const rl = readline.createInterface({
        input: fileStream,
        crlfDelay: Infinity,
      });

      let inputTokens = 0;
      let outputTokens = 0;
      let stepCount = 0;
      let userMessageCount = 0;
      let modelResponseCount = 0;
      let toolCallCount = 0;
      let lastDetectedModelKey: string | undefined;
      let lastDetectedModelName: string | undefined;
      let title = `Conversation ${conversationId.slice(0, 8)}`;

      // Active model context for step-level tracking
      const defaultResolved = resolveModelPricing(pricing.modelKey || DEFAULT_MODEL_KEY);
      let currentModelKey = defaultResolved.key;
      let currentModelName = defaultResolved.name;

      // Map to accumulate token breakdown per model
      const modelBreakdown: Record<string, ModelUsageMetrics> = {};

      const addModelTokens = (mKey: string, mName: string, inT: number, outT: number, isNewStep: boolean) => {
        if (!modelBreakdown[mKey]) {
          modelBreakdown[mKey] = {
            modelKey: mKey,
            modelName: mName,
            inputTokens: 0,
            outputTokens: 0,
            totalTokens: 0,
            estimatedCostUsd: 0,
            stepCount: 0,
          };
        }
        modelBreakdown[mKey].inputTokens += inT;
        modelBreakdown[mKey].outputTokens += outT;
        modelBreakdown[mKey].totalTokens += inT + outT;
        if (isNewStep) {
          modelBreakdown[mKey].stepCount = (modelBreakdown[mKey].stepCount || 0) + 1;
        }
      };

      for await (const line of rl) {
        if (!line.trim()) continue;

        try {
          const step: RawTranscriptStep = JSON.parse(line);
          stepCount++;

          // Detect active model changes from step content or properties
          const rawModel = this.extractModelFromStep(step);
          if (rawModel) {
            const resolved = resolveModelPricing(rawModel);
            currentModelKey = resolved.key;
            currentModelName = resolved.name;
            lastDetectedModelKey = resolved.key;
            lastDetectedModelName = resolved.name;
          }

          const isUser = step.type === 'USER_INPUT' || step.source === 'USER_EXPLICIT';
          const isModel = step.type === 'PLANNER_RESPONSE' || step.source === 'MODEL';
          const isSystem = step.type === 'SYSTEM_MESSAGE' || step.source === 'SYSTEM';

          let stepInputTokens = 0;
          let stepOutputTokens = 0;

          // Extract content tokens
          if (step.content) {
            const tokens = this.tokenizer.countTokens(step.content);
            if (isUser || isSystem) {
              stepInputTokens += tokens;
              if (isUser) {
                userMessageCount++;
                if (userMessageCount === 1) {
                  // Clean first message as session title preview
                  const cleanContent = step.content.replace(/<[^>]+>/g, '').trim();
                  if (cleanContent) {
                    title = cleanContent.length > 40 ? cleanContent.slice(0, 37) + '...' : cleanContent;
                  }
                }
              }
            } else if (isModel) {
              stepOutputTokens += tokens;
              modelResponseCount++;
            } else {
              // Default to input tokens for tools/metadata/context
              stepInputTokens += tokens;
            }
          }

          // Extract tool calls tokens (generated by model -> Output tokens)
          if (step.tool_calls && Array.isArray(step.tool_calls) && step.tool_calls.length > 0) {
            toolCallCount += step.tool_calls.length;
            for (const call of step.tool_calls) {
              if (call.name) {
                stepOutputTokens += this.tokenizer.countTokens(call.name);
              }
              if (call.args) {
                stepOutputTokens += this.tokenizer.countObjectTokens(call.args);
              }
            }
          }

          inputTokens += stepInputTokens;
          outputTokens += stepOutputTokens;

          // Credit tokens to active model
          addModelTokens(currentModelKey, currentModelName, stepInputTokens, stepOutputTokens, true);
        } catch (jsonErr) {
          // Skip malformed JSON lines
        }
      }

      // Calculate cost per model and aggregate total session cost
      let totalCalculatedCost = 0;
      for (const mKey of Object.keys(modelBreakdown)) {
        const m = modelBreakdown[mKey];
        const resolved = resolveModelPricing(mKey);
        const mPricing: PricingRates = pricing.isAutoDetected
          ? {
              modelName: resolved.name,
              modelKey: resolved.key,
              inputPerMillion: resolved.inputPerMillion,
              outputPerMillion: resolved.outputPerMillion,
              isAutoDetected: true,
            }
          : pricing;
        m.estimatedCostUsd = this.calculateCost(m.inputTokens, m.outputTokens, mPricing);
        totalCalculatedCost += m.estimatedCostUsd;
      }


      const totalTokens = inputTokens + outputTokens;
      const roundedTotalCost = Math.round(totalCalculatedCost * 10000) / 10000;

      const metrics: TokenMetrics = {
        inputTokens,
        outputTokens,
        totalTokens,
        estimatedCostUsd: roundedTotalCost,
      };

      return {
        conversationId,
        title,
        lastUpdated: stats.mtimeMs,
        transcriptPath: filePath,
        stepCount,
        userMessageCount,
        modelResponseCount,
        toolCallCount,
        detectedModel: lastDetectedModelKey || currentModelKey,
        detectedModelName: lastDetectedModelName || currentModelName,
        modelBreakdown,
        metrics,
      };
    } catch (err) {
      console.error(`[AntigravityTokenCounter] Error reading transcript at ${filePath}:`, err);
      return null;
    }
  }

  /**
   * Extracts model name/selection from transcript step data or settings logs
   */
  private extractModelFromStep(step: RawTranscriptStep): string | null {
    const anyStep = step as Record<string, unknown>;
    if (typeof anyStep.model === 'string' && anyStep.model.trim()) {
      return anyStep.model.trim();
    }
    if (typeof anyStep.model_name === 'string' && anyStep.model_name.trim()) {
      return anyStep.model_name.trim();
    }
    if (anyStep.metadata && typeof anyStep.metadata === 'object') {
      const meta = anyStep.metadata as Record<string, unknown>;
      if (typeof meta.model === 'string' && meta.model.trim()) {
        return meta.model.trim();
      }
    }

    if (step.content) {
      // Detect <USER_SETTINGS_CHANGE> Model Selection ...
      const settingsMatch = step.content.match(
        /Model\s+Selection[`"']?\s*(?:from\s+[^to\n\r]+)?\s*to\s+([A-Za-z0-9\.\-\s]+(?:\([^\)]+\))?)/i
      );
      if (settingsMatch && settingsMatch[1]) {
        return settingsMatch[1].replace(/[.\r\n]+$/, '').trim();
      }

      // Detect <model_selection> or <model> tags
      const modelTagMatch = step.content.match(/<(?:model_selection|model_name|model)>([^<]+)<\//i);
      if (modelTagMatch && modelTagMatch[1]) {
        return modelTagMatch[1].trim();
      }
    }

    return null;
  }

  /**
   * Computes USD cost based on token counts and pricing rates.
   */
  public calculateCost(inputTokens: number, outputTokens: number, pricing: PricingRates): number {
    const inputCost = (inputTokens / 1_000_000) * pricing.inputPerMillion;
    const outputCost = (outputTokens / 1_000_000) * pricing.outputPerMillion;
    return Math.round((inputCost + outputCost) * 10000) / 10000; // Round to 4 decimal places
  }
}

